`timescale 1ns/1ps

module tb_gru_luts;
    localparam SIGMOID_FILE = "../mem/lut/sigmoid_half_lut_q15.mem";
    localparam TANH_FILE    = "../mem/lut/tanh_half_lut_q15.mem";

    logic clk = 1'b0;
    logic rst_n = 1'b0;
    logic in_valid = 1'b0;
    logic signed [15:0] sigmoid_in = '0;
    logic signed [15:0] tanh_in = '0;
    logic sigmoid_valid;
    logic tanh_valid;
    logic signed [15:0] sigmoid_out;
    logic signed [15:0] tanh_out;

    logic signed [15:0] sigmoid_expected [0:255];
    logic signed [15:0] tanh_expected [0:255];
    integer errors = 0;
    integer checks = 0;
    integer sample;

    always #5 clk = ~clk;

    sigmoid_lut #(.MEM_FILE(SIGMOID_FILE)) u_sigmoid (
        .clk(clk), .rst_n(rst_n),
        .in_valid(in_valid), .in_data(sigmoid_in),
        .out_valid(sigmoid_valid), .out_data(sigmoid_out)
    );

    tanh_lut #(.MEM_FILE(TANH_FILE)) u_tanh (
        .clk(clk), .rst_n(rst_n),
        .in_valid(in_valid), .in_data(tanh_in),
        .out_valid(tanh_valid), .out_data(tanh_out)
    );

    function automatic integer absolute_value(input integer raw_value);
        begin
            if (raw_value < 0)
                absolute_value = -raw_value;
            else
                absolute_value = raw_value;
        end
    endfunction

    function automatic integer sigmoid_index(input integer raw_value);
        integer product;
        integer magnitude;
        begin
            magnitude = absolute_value(raw_value);
            if (magnitude >= 3193)
                sigmoid_index = 255;
            else begin
                product = magnitude * 83741;
                sigmoid_index = product >>> 20;
            end
        end
    endfunction

    function automatic integer tanh_index(input integer raw_value);
        integer product;
        integer magnitude;
        begin
            magnitude = absolute_value(raw_value);
            if (magnitude >= 1774)
                tanh_index = 255;
            else begin
                product = magnitude * 150725;
                tanh_index = product >>> 20;
            end
        end
    endfunction

    task automatic drive_and_check(
        input integer sigmoid_raw,
        input integer tanh_raw
    );
        integer sig_idx;
        integer tanh_idx_value;
        integer expected_sigmoid_value;
        integer expected_tanh_value;
        begin
            sig_idx = sigmoid_index(sigmoid_raw);
            tanh_idx_value = tanh_index(tanh_raw);
            if (sigmoid_raw < 0)
                expected_sigmoid_value = 32768 - sigmoid_expected[sig_idx];
            else
                expected_sigmoid_value = sigmoid_expected[sig_idx];
            if (tanh_raw < 0)
                expected_tanh_value = -tanh_expected[tanh_idx_value];
            else
                expected_tanh_value = tanh_expected[tanh_idx_value];

            @(negedge clk);
            in_valid = 1'b1;
            sigmoid_in = sigmoid_raw;
            tanh_in = tanh_raw;

            @(posedge clk);
            @(negedge clk);
            checks = checks + 1;

            if (!sigmoid_valid || (sigmoid_out !== expected_sigmoid_value)) begin
                $display("SIGMOID ERROR: in=%0d idx=%0d got=%0d expected=%0d",
                         sigmoid_raw, sig_idx, sigmoid_out,
                         expected_sigmoid_value);
                errors = errors + 1;
            end

            if (!tanh_valid || (tanh_out !== expected_tanh_value)) begin
                $display("TANH ERROR: in=%0d idx=%0d got=%0d expected=%0d",
                         tanh_raw, tanh_idx_value, tanh_out,
                         expected_tanh_value);
                errors = errors + 1;
            end
        end
    endtask

    initial begin
        $readmemh(SIGMOID_FILE, sigmoid_expected, 0, 255);
        $readmemh(TANH_FILE, tanh_expected, 0, 255);

        repeat (3) @(posedge clk);
        rst_n = 1'b1;

        // Exhaustively verify every possible signed 16-bit input. This covers
        // both saturation regions, both exact endpoints, and every interior
        // index generated by the constant-multiply address conversion.
        for (sample = -32768; sample <= 32767; sample = sample + 1)
            drive_and_check(sample, sample);

        @(negedge clk);
        in_valid = 1'b0;
        @(posedge clk);
        @(negedge clk);
        if (sigmoid_valid || tanh_valid) begin
            $display("VALID ERROR: out_valid did not follow in_valid");
            errors = errors + 1;
        end

        if (errors == 0)
            $display("PASS: Sigmoid/Tanh LUTs, checks=%0d", checks);
        else
            $display("FAIL: Sigmoid/Tanh LUT errors=%0d", errors);

        $finish;
    end
endmodule
